services:
  convertx:
    build:
      context: .
      # dockerfile: Debian.Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - ACCOUNT_REGISTRATION=true
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234
      - ALLOW_UNAUTHENTICATED=true
    ports:
      - 3000:3000
