services:
  convertx:
    build:
      context: .
    volumes:
      - ./data:/app/data
    environment:
      - ACCOUNT_REGISTRATION=true
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234
    ports:
      - 3000:3000
